In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
website = "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE169nnn/GSE169598/matrix/GSE169598_series_matrix.txt.gz"
data_path = "fajciarky_data/data.txt"
data_path_zip = "fajciarky_data/data.txt.gz"

In [ ]:
# toto ich nacita rovno zo stranky ale my ich potrebujeme mat lokalne lebo potrebujeme niektore tie koment riadky a tie sa pri nacitani z webu stratia

# df = pd.read_csv(website, sep="\t", comment="!", header=0)

In [3]:
# keby nejde curl tak wget sa da takto 

# import os
# if not os.path.exists("fajciarky_data"):
#     os.makedirs("fajciarky_data")
# !wget -O $data_path_zip $website

!curl $website --create-dirs -o $data_path_zip
!gunzip $data_path_zip

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  333M  100  333M    0     0  22.7M      0  0:00:14  0:00:14 --:--:-- 29.6M:00:06 26.8M

In [3]:
with open(data_path, "r") as f:
    for i, line in enumerate(f):
        if i > 1000:
            break
        if line.startswith("\"ID_REF\""):
            skiprow = i

df = pd.read_csv(data_path, sep="\t", comment="!", header=0, skiprows=skiprow)
# print(df.head())

In [6]:
df.set_index("ID_REF", inplace=True)
df.head()

,GSM5210464,GSM5210465,GSM5210466,GSM5210467,GSM5210468,GSM5210469,GSM5210470,GSM5210471,GSM5210472,GSM5210473,...,GSM5210559,GSM5210560,GSM5210561,GSM5210562,GSM5210563,GSM5210564,GSM5210565,GSM5210566,GSM5210567,GSM5210568
ID_REF,,,,,,,,,,,,,,,,,,,,,
cg00000029,0.006342,0.101510,0.042916,0.101567,0.114736,0.129332,0.134621,0.105126,0.116374,0.115263,...,0.031195,0.073563,0.033745,0.068623,0.080539,0.076037,0.068573,0.058533,0.087450,0.056575
cg00000109,0.911428,0.924547,0.926018,0.920207,0.925702,0.920111,0.928904,0.930301,0.936867,0.929511,...,0.941892,0.926477,0.932000,0.919153,0.916438,0.930748,0.928532,0.923054,0.925112,0.932230
cg00000155,0.948963,0.936607,0.946371,0.951434,0.949158,0.941937,0.940608,0.952269,0.940826,0.945244,...,0.941315,0.949903,0.939967,0.947754,0.945189,0.944838,0.935689,0.947255,0.944136,0.948023
cg00000158,0.955034,0.954614,0.964843,0.958018,0.954761,0.952986,0.948309,0.949837,0.964955,0.958335,...,0.953417,0.956355,0.951742,0.951842,0.953409,0.962594,0.956193,0.953015,0.958268,0.948005
cg00000165,0.602739,0.654239,0.635608,0.514626,0.569226,0.700535,0.684166,0.778416,0.819973,0.606592,...,0.739746,0.782725,0.735866,0.628380,0.742475,0.669129,0.716647,0.685260,0.532178,0.724952

In [7]:
df = df.astype(float)

In [8]:
df = df.T

In [9]:
df.head()

ID_REF,cg00000029,cg00000109,cg00000155,cg00000158,cg00000165,cg00000221,cg00000236,cg00000289,cg00000292,cg00000321,...,cg27665860,cg27665913,cg27665925,cg27665978,cg27665985,cg27666046,cg27666049,cg27666060,cg27666108,cg27666123
GSM5210464,0.006342,0.911428,0.948963,0.955034,0.602739,0.919096,0.829139,0.854049,0.640229,0.568796,...,0.683343,0.803646,0.010299,0.868090,0.033417,0.210715,0.358502,0.821699,0.305286,0.370756
GSM5210465,0.101510,0.924547,0.936607,0.954614,0.654239,0.912881,0.864159,0.833509,0.706422,0.642472,...,0.542085,0.781690,0.010684,0.819956,0.052835,0.148981,0.285947,0.768324,0.288413,0.305624
GSM5210466,0.042916,0.926018,0.946371,0.964843,0.635608,0.915767,0.825087,0.844758,0.597064,0.607435,...,0.607113,0.750724,0.010983,0.790859,0.059366,0.237946,0.146520,0.712438,0.224894,0.297253
GSM5210467,0.101567,0.920207,0.951434,0.958018,0.514626,0.910884,0.828211,0.776141,0.575917,0.461922,...,0.509281,0.750781,0.011266,0.850157,0.065203,0.182320,0.453670,0.671866,0.222262,0.255361
GSM5210468,0.114736,0.925702,0.949158,0.954761,0.569226,0.908985,0.819156,0.792884,0.680974,0.634972,...,0.585585,0.817459,0.011469,0.835717,0.052993,0.238045,0.543655,0.716242,0.331210,0.361257

In [ ]:
times_row = "!Sample_title"
submission_date_row = "!Sample_submission_date"
contact_name_row = "!Sample_contact_name"
data_processing_row = "!Sample_data_processing"
scan_protocol_row = "!Sample_scan_protocol"
hyb_protocol_row = "!Sample_hyb_protocol"
extract_protocol_row = "!Sample_extract_protocol_ch1"
molecule_row = "!Sample_molecule_ch1"
sex_row = "!Sample_characteristics_ch1" # first
gestational_age_row = "!Sample_characteristics_ch1" # second
smoke_type_row = "!Sample_characteristics_ch1" # third
debug = "\"cg00000029\""

wanted_rows = [
    times_row,
    submission_date_row,
    contact_name_row,
    data_processing_row,
    scan_protocol_row,
    hyb_protocol_row,
    extract_protocol_row,
    molecule_row,
    sex_row,
    gestational_age_row,
    smoke_type_row,
    # debug
]

# open only first 100 lines of the file to find the wanted rows

with open(data_path, "r") as file:
    j = 0
    for i, line in enumerate(file):
        if i >= 100:
            break
        if line.startswith(tuple(wanted_rows)):
            row_name, row_data = line.split("\t", 1)
            if row_name == smoke_type_row:
                row_name = ["sex", "gestational_age", "smoke_type"][j]
                j += 1
            else:
                row_name = row_name.lstrip("!Sample_").rstrip("_ch1") # TODO why does it remove m from !Sample_molecule_ch1? and e from !Sample_extract_protocol_ch1?

            df[row_name] = row_data.strip().split("\t")

ID_REF      cg00000029  cg00000109  cg00000155  cg00000158  cg00000165  \
GSM5210557    0.075395    0.929582    0.940039    0.956119    0.655137
GSM5210558    0.091453    0.931727    0.949153    0.960188    0.702239
GSM5210559    0.031195    0.941892    0.941315    0.953417    0.739746
GSM5210560    0.073563    0.926477    0.949903    0.956355    0.782725
GSM5210561    0.033745    0.932000    0.939967    0.951742    0.735866
GSM5210562    0.068623    0.919153    0.947754    0.951842    0.628380
GSM5210563    0.080539    0.916438    0.945189    0.953409    0.742475
GSM5210564    0.076037    0.930748    0.944838    0.962594    0.669129
GSM5210565    0.068573    0.928532    0.935689    0.956193    0.716647
GSM5210566    0.058533    0.923054    0.947255    0.953015    0.685260
GSM5210567    0.087450    0.925112    0.944136    0.958268    0.532178
GSM5210568    0.056575    0.932230    0.948023    0.948005    0.724952

ID_REF      cg00000221  cg00000236  cg00000289  cg00000292  cg00000321  ...  \
GSM5210557    0.916220    0.835585    0.818062    0.613154    0.689502  ...
GSM5210558    0.924422    0.844984    0.847813    0.682828    0.426759  ...
GSM5210559    0.919224    0.852114    0.799358    0.610009    0.617789  ...
GSM5210560    0.913532    0.848975    0.824494    0.646407    0.578108  ...
GSM5210561    0.910877    0.874445    0.811092    0.538101    0.470552  ...
GSM5210562    0.899494    0.823794    0.803820    0.639810    0.548366  ...
GSM5210563    0.895223    0.872854    0.780552    0.653798    0.662156  ...
GSM5210564    0.920017    0.845113    0.832711    0.675962    0.632108  ...
GSM5210565    0.908093    0.866134    0.812491    0.576117    0.583606  ...
GSM5210566    0.904958    0.849140    0.852171    0.588527    0.551871  ...
GSM5210567    0.899524    0.889254    0.788550    0.647773    0.553538  ...
GSM5210568    0.918041    0.833349    0.731934    0.664596    0.619473  ...

ID_REF      submission_date       sex                gestational_age  \
GSM5210557    "Mar 25 2021"  "Sex: F"  "gestational age weeks: 39.3"
GSM5210558    "Mar 25 2021"  "Sex: F"  "gestational age weeks: 38.0"
GSM5210559    "Mar 25 2021"  "Sex: M"  "gestational age weeks: 42.0"
GSM5210560    "Mar 25 2021"  "Sex: F"  "gestational age weeks: 38.9"
GSM5210561    "Mar 25 2021"  "Sex: F"  "gestational age weeks: 41.1"
GSM5210562    "Mar 25 2021"  "Sex: F"  "gestational age weeks: 37.1"
GSM5210563    "Mar 25 2021"  "Sex: F"  "gestational age weeks: 39.0"
GSM5210564    "Mar 25 2021"  "Sex: F"  "gestational age weeks: 37.0"
GSM5210565    "Mar 25 2021"  "Sex: F"  "gestational age weeks: 37.9"
GSM5210566    "Mar 25 2021"  "Sex: F"  "gestational age weeks: 39.0"
GSM5210567    "Mar 25 2021"  "Sex: F"  "gestational age weeks: 39.0"
GSM5210568    "Mar 25 2021"  "Sex: F"  "gestational age weeks: 39.7"

ID_REF                smoke_type        olecule  \
GSM5210557     "smoking: smoker"  "genomic DNA"
GSM5210558     "smoking: smoker"  "genomic DNA"
GSM5210559  "smoking: nonsmoker"  "genomic DNA"
GSM5210560  "smoking: nonsmoker"  "genomic DNA"
GSM5210561     "smoking: smoker"  "genomic DNA"
GSM5210562     "smoking: smoker"  "genomic DNA"
GSM5210563     "smoking: smoker"  "genomic DNA"
GSM5210564     "smoking: smoker"  "genomic DNA"
GSM5210565     "smoking: smoker"  "genomic DNA"
GSM5210566     "smoking: smoker"  "genomic DNA"
GSM5210567  "smoking: nonsmoker"  "genomic DNA"
GSM5210568  "smoking: nonsmoker"  "genomic DNA"

ID_REF                                        xtract_protocol  \
GSM5210557  "DNA, RNA, and miRNA were simultaneously extra...
GSM5210558  "DNA, RNA, and miRNA were simultaneously extra...
GSM5210559  "DNA, RNA, and miRNA were simultaneously extra...
GSM5210560  "DNA, RNA, and miRNA were simultaneously extra...
GSM5210561  "DNA, RNA, and miRNA were simultaneously extra...
GSM5210562  "DNA, RNA, and miRNA were simultaneously extra...
GSM5210563  "DNA, RNA, and miRNA were simultaneously extra...
GSM5210564  "DNA, RNA, and miRNA were simultaneously extra...
GSM5210565  "DNA, RNA, and miRNA were simultaneously extra...
GSM5210566  "DNA, RNA, and miRNA were simultaneously extra...
GSM5210567  "DNA, RNA, and miRNA were simultaneously extra...
GSM5210568  "DNA, RNA, and miRNA were simultaneously extra...

ID_REF                      hyb_protocol  \
GSM5210557  "standard Illumina protocol"
GSM5210558  "standard Illumina protocol"
GSM5210559  "standard Illumina protocol"
GSM5210560  "standard Illumina protocol"
GSM5210561  "standard Illumina protocol"
GSM5210562  "standard Illumina protocol"
GSM5210563  "standard Illumina protocol"
GSM5210564  "standard Illumina protocol"
GSM5210565  "standard Illumina protocol"
GSM5210566  "standard Illumina protocol"
GSM5210567  "standard Illumina protocol"
GSM5210568  "standard Illumina protocol"

ID_REF                                          scan_protocol  \
GSM5210557  "Placental DNAM was assessed on the Methylatio...
GSM5210558  "Placental DNAM was assessed on the Methylatio...
GSM5210559  "Placental DNAM was assessed on the Methylatio...
GSM5210560  "Placental DNAM was assessed on the Methylatio...
GSM5210561  "Placental DNAM was assessed on the Methylatio...
GSM5210562  "Placental DNAM was assessed on the Methylatio...
GSM5210563  "Placental DNAM was assessed on the Methylatio...
GSM5210564  "Placental DNAM was assessed on the Methylatio...
GSM5210565  "Placental DNAM was assessed on the Methylatio...
GSM5210566  "Placental DNAM was assessed on the Methylatio...
GSM5210567  "Placental DNAM was assessed on the Methylatio...
GSM5210568  "Placental DNAM was assessed on the Methylatio...

ID_REF                                        data_processing  \
GSM5210557  "Data normalization and QC were performed usin...
GSM5210558  "Data normalization and QC were performed usin...
GSM5210559  "Data normalization and QC were performed usin...
GSM5210560  "Data normalization and QC were performed usin...
GSM5210561  "Data normalization and QC were performed usin...
GSM5210562  "Data normalization and QC were performed usin...
GSM5210563  "Data normalization and QC were performed usin...
GSM5210564  "Data normalization and QC were performed usin...
GSM5210565  "Data normalization and QC were performed usin...
GSM5210566  "Data normalization and QC were performed usin...
GSM5210567  "Data normalization and QC were performed usin...
GSM5210568  "Data normalization and QC were performed usin...

ID_REF                             contact_name
GSM5210557  "Lyndsey,Elizabeth,Shorey-Kendrick"
GSM5210558  "Lyndsey,Elizabeth,Shorey-Kendrick"
GSM5210559  "Lyndsey,Elizabeth,Shorey-Kendrick"
GSM5210560  "Lyndsey,Elizabeth,Shorey-Kendrick"
GSM5210561  "Lyndsey,Elizabeth,Shorey-Kendrick"
GSM5210562  "Lyndsey,Elizabeth,Shorey-Kendrick"
GSM5210563  "Lyndsey,Elizabeth,Shorey-Kendrick"
GSM5210564  "Lyndsey,Elizabeth,Shorey-Kendrick"
GSM5210565  "Lyndsey,Elizabeth,Shorey-Kendrick"
GSM5210566  "Lyndsey,Elizabeth,Shorey-Kendrick"
GSM5210567  "Lyndsey,Elizabeth,Shorey-Kendrick"
GSM5210568  "Lyndsey,Elizabeth,Shorey-Kendrick"

[12 rows x 714677 columns]

In [28]:
df.columns

Index(['cg00000029', 'cg00000109', 'cg00000155', 'cg00000158', 'cg00000165',
       'cg00000221', 'cg00000236', 'cg00000289', 'cg00000292', 'cg00000321',
       ...
       'submission_date', 'sex', 'gestational_age', 'smoke_type', 'olecule',
       'xtract_protocol', 'hyb_protocol', 'scan_protocol', 'data_processing',
       'contact_name'],
      dtype='str', name='ID_REF', length=714677)